#' Title
#'
#' @param data a data frame containing the columns modal_age_closest, modal_age_low, age, corresponding to the modal age closest to the mean, the lowest modal age, and an age-reading, respectively. Typically the output generated by the function Compute_modes.
#' @param min_age The minimum age, defaults to -1
#' @param max_age The  maximum age, defaults to infinity
#'
#' @return a data frame with all ages capped at min_age and max_age
#' @export
#'
#' @examples
#' file_path = system.file("extdata",
#'                         "NSS_herring_scales.csv",
#'                          package = "ParametricAEM")
#' data_nss_scales = read.csv(file_path, sep = ",")
#' data_exp = data_nss_scales[data_nss_scales$expertise == 1, ] # Extract experts
#' data_exp = data_exp[data_exp$age > 0, ]
#' data_analysis = Compute_modes(data_exp)
#' data_analysis_capped = Cap_ages(data_analysis)
Cap_ages = function(data, min_age = -1, max_age = Inf){
    data$modal_age_closest[data$modal_age_closest > max_age] = max_age
    data$modal_age_closest[data$modal_age_closest < min_age] = min_age
    data$modal_age_low[data$modal_age_low > max_age] = max_age
    data$modal_age_low[data$modal_age_low < min_age] = min_age
    data$age[data$age > max_age] = max_age
    data$age[data$age < min_age] = min_age
    return(data)
}
